// <auto-generated />
using ComicsUniverse.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicsUniverse.DataAccess.Migrations
{
    [DbContext(typeof(ComicsUniverseContext))]
    partial class ComicsUniverseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CharacterSuperPower", b =>
                {
                    b.Property<int>("CharactersCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("PowersSuperPowerId")
                        .HasColumnType("int");

                    b.HasKey("CharactersCharacterId", "PowersSuperPowerId");

                    b.HasIndex("PowersSuperPowerId");

                    b.ToTable("CharacterSuperPower");

                    b.HasData(
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 1
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 2
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 3
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 4
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 5
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 6
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 7
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 8
                        },
                        new
                        {
                            CharactersCharacterId = 1,
                            PowersSuperPowerId = 9
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            PowersSuperPowerId = 14
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            PowersSuperPowerId = 15
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            PowersSuperPowerId = 16
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            PowersSuperPowerId = 17
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            PowersSuperPowerId = 18
                        },
                        new
                        {
                            CharactersCharacterId = 2,
                            PowersSuperPowerId = 19
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            PowersSuperPowerId = 1
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            PowersSuperPowerId = 2
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            PowersSuperPowerId = 3
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            PowersSuperPowerId = 4
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            PowersSuperPowerId = 10
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            PowersSuperPowerId = 11
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            PowersSuperPowerId = 12
                        },
                        new
                        {
                            CharactersCharacterId = 3,
                            PowersSuperPowerId = 13
                        },
                        new
                        {
                            CharactersCharacterId = 4,
                            PowersSuperPowerId = 10
                        },
                        new
                        {
                            CharactersCharacterId = 4,
                            PowersSuperPowerId = 20
                        },
                        new
                        {
                            CharactersCharacterId = 4,
                            PowersSuperPowerId = 21
                        });
                });

            modelBuilder.Entity("ComicsUniverse.DataAccess.Model.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Universe")
                        .HasColumnType("int");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Alias = "Clark Kent, Kal-El",
                            Description = "Faster than a speeding bullet, more powerful than a locomotive… The Man of Steel fights a never-ending battle for truth, justice, and the American way. From his blue uniform to his flowing red cape to the 'S' shield on his chest, Superman is one of the most immediately recognizable and beloved DC Super Heroes of all time. The Man of Steel is the ultimate symbol of truth, justice, and hope. He is the world's first Super Hero and a guiding light to all.",
                            Name = "Superman",
                            Occupation = "Reporter",
                            ProfileImage = "Superman.jpg",
                            Universe = 1
                        },
                        new
                        {
                            CharacterId = 2,
                            Alias = "Hal Jordan",
                            Description = "Test pilot Hal Jordan went from being a novelty, the first-ever human Green Lantern, to one of the most legendary Lanterns to ever wield a power ring. Hal Jordan’s life was changed twice by crashing aircraft. The first time was when he witnessed the death of his father, pilot Martin Jordan. The second was when, as an adult and trained pilot himself, he was summoned to the crashed wreckage of a spaceship belonging to an alien named Abin Sur. Abin explained that he was a member of the Green Lantern Corps, an organization of beings from across the cosmos, armed with power rings fueled by the green energy of all willpower in the universe. Upon his death, Abin entrusted his ring and duties as the Green Lantern of Earth’s space sector to Hal Jordan.",
                            Name = "Green Lantern",
                            Occupation = "Test pilot",
                            ProfileImage = "GreenLantern.jpg",
                            Universe = 1
                        },
                        new
                        {
                            CharacterId = 3,
                            Alias = "Diana Prince",
                            Description = "Beautiful as Aphrodite, wise as Athena, swifter than Hermes, and stronger than Hercules, Princess Diana of Themyscira fights for peace in Man's World. One of the most beloved and iconic DC Super Heroes of all time, Wonder Woman has stood for nearly eighty years as a symbol of truth, justice and equality to people everywhere. Raised on the hidden island of Themyscira, also known as Paradise Island, Diana is an Amazon, like the figures of Greek legend, and her people's gift to humanity.",
                            Name = "Wonder Woman",
                            ProfileImage = "WonderWoman.jpg",
                            Universe = 1
                        },
                        new
                        {
                            CharacterId = 4,
                            Alias = "Christopher Smith",
                            Description = "A huge, hulking specimen with muscles on his muscles, Christopher Smith is a world class marksman - just like his fellow Suicide Squad member, Bloodsport. (But if you ask him, better.) Having adopted the name Peacemaker, Christopher is more than willing to fight, kill and even start a war... all in the name of keeping the peace.",
                            Name = "Peacemaker",
                            ProfileImage = "Peacemaker.jpg",
                            Universe = 1
                        });
                });

            modelBuilder.Entity("ComicsUniverse.DataAccess.Model.SuperPower", b =>
                {
                    b.Property<int>("SuperPowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuperPowerId");

                    b.ToTable("SuperPowers");

                    b.HasData(
                        new
                        {
                            SuperPowerId = 1,
                            Name = "healing factor"
                        },
                        new
                        {
                            SuperPowerId = 2,
                            Name = "super strength"
                        },
                        new
                        {
                            SuperPowerId = 3,
                            Name = "flight"
                        },
                        new
                        {
                            SuperPowerId = 4,
                            Name = "invulnerability"
                        },
                        new
                        {
                            SuperPowerId = 5,
                            Name = "super speed"
                        },
                        new
                        {
                            SuperPowerId = 6,
                            Name = "heat vision"
                        },
                        new
                        {
                            SuperPowerId = 7,
                            Name = "freeze breath"
                        },
                        new
                        {
                            SuperPowerId = 8,
                            Name = "x-ray vision"
                        },
                        new
                        {
                            SuperPowerId = 9,
                            Name = "superhuman hearing"
                        },
                        new
                        {
                            SuperPowerId = 10,
                            Name = "combat skill"
                        },
                        new
                        {
                            SuperPowerId = 11,
                            Name = "combat strategy"
                        },
                        new
                        {
                            SuperPowerId = 12,
                            Name = "superhuman agility"
                        },
                        new
                        {
                            SuperPowerId = 13,
                            Name = "magic weaponry"
                        },
                        new
                        {
                            SuperPowerId = 14,
                            Name = "hard light constructs"
                        },
                        new
                        {
                            SuperPowerId = 15,
                            Name = "instant weaponry"
                        },
                        new
                        {
                            SuperPowerId = 16,
                            Name = "force fields"
                        },
                        new
                        {
                            SuperPowerId = 17,
                            Name = "flight"
                        },
                        new
                        {
                            SuperPowerId = 18,
                            Name = "durability"
                        },
                        new
                        {
                            SuperPowerId = 19,
                            Name = "alien technology"
                        },
                        new
                        {
                            SuperPowerId = 20,
                            Name = "top level marksman"
                        },
                        new
                        {
                            SuperPowerId = 21,
                            Name = "weapons expert"
                        });
                });

            modelBuilder.Entity("CharacterSuperPower", b =>
                {
                    b.HasOne("ComicsUniverse.DataAccess.Model.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComicsUniverse.DataAccess.Model.SuperPower", null)
                        .WithMany()
                        .HasForeignKey("PowersSuperPowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
